import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { I18nProvider } from "./context/translate-api";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Get the initial locale from the cookie on the server
  const cookieStore = await cookies();
  const initialLocale = cookieStore.get("lang")?.value || "ar";

  return (
    <html lang={initialLocale} dir={initialLocale === "ar" ? "rtl" : "ltr"}>
      <body
        className={`${inter.className} ${geistSans.variable} ${geistMono.variable}`}
      >
        <I18nProvider initialLocal={initialLocale}>
          <Toaster position="top-center" reverseOrder={false} />
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
